repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-added-large-files
    -   id: mixed-line-ending
-   repo: local
    hooks:
    -   id: check
        name: "cargo check"
        language: "system"
        files: runtime/(.*\.rs)|(Cargo\.*)
        pass_filenames: false
        entry: "cargo check --manifest-path=runtime/Cargo.toml"
    -   id: format
        name: "rustfmt"
        language: "system"
        files: runtime/(.*\.rs)
        entry: "rustfmt"
    -   id: test
        name: "cargo test"
        language: "system"
        pass_filenames: false
        files: runtime/(.*\.rs)|(Cargo\.*)
        entry: "cargo test --manifest-path=runtime/Cargo.toml"
