[package]
name = "notred"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
json = '*'
quick-error = "^2.0.0"
counted-array = "^0.1.2"
log = '^0.4.14'
