[package]
name = "notred"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
quick-error = "2.0.1"
log = "0.4.17"
serde = "1.0.143"
serde_json = "1.0.83"
typetag = "0.2.3"
